spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  devtools:
    restart:
      exclude: templates/**,static/**  #这两个目录下的静态资源修改，不引发热加载
  mvc:
    static-path-pattern: /static/**
server:
  error:
    whitelabel:
      enabled: false #禁用错误页面
# qiniu 注意替换成自己申请的配置
qiniu:
     AccessKey: GVD-MVQEoOiJOt7yNBDo-JrOKWHB33eZN2JmDFC6
     SecretKey: sHnl57ZXtStejn7GgY5VF3lnm1CxMJ3hcayexAWz
     Bucket: lakers
     cdn:
        prefix: http://7xo6gy.com1.z0.glb.clouddn.com/